set -g mouse on
set -g status-interval 5
set -g focus-events on
set -g status-position bottom
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g status-left "#[fg=#89b4fa] #S "
setw -g window-status-format " #I:#W "
setw -g window-status-current-format "#[fg=#f9e2af,bold] #I:#W "
set -g status-right '#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD)'
setw -g automatic-rename on
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1
