[window]
opacity = 1
decorations = "Full"
decorations_theme_variant = "Dark"

[window.padding]
x = 10
y = 5

[colors.primary]
background = '#100f0f'

[font]
size = 11.0

[mouse]
hide_when_typing = true
